server {
    if ($host = sapio.ovh) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    listen 80;
    server_name sapio.ovh;
    return 301 https://server.sapio.ovh$request_uri;
}

server {
    listen 443 ssl;
    server_name server.sapio.ovh;

    ssl on;
    ssl_certificate /etc/letsencrypt/live/server.sapio.ovh/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/server.sapio.ovh/privkey.pem;

    # Block AI bots
    if ($http_user_agent ~* (Amazonbot|anthropic-ai|Applebot-Extended|AwarioRssBot|AwarioSmartBot|Bytespider|CCBot|ChatGPT-User|Claude-Web|ClaudeBot|cohere-ai|DataForSeoBot|Diffbot|FacebookBot|Google-Extended|GPTBot|ImagesiftBot|magpie-crawler|omgili|Omgilibot|peer39_crawler|PerplexityBot|YouBot)) {
        return 403;
    }

    location /fdroid/ {
        alias /var/www/fdroid/;
        autoindex off;
        default_type application/octet-stream;
    }

    location / {
        proxy_pass http://strapi;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }
}
